solve two warnings re CUDA
ArgumentError: Package Zygote does not have CUDA in its dependencies
WARNING: using CUDA.trim in module Zygote conflicts with an existing identifier